default_language_version:
    python: python3

repos:
-   repo: local
    hooks:
    - id: pre-commit-docker
      name: pre-commit-docker
      entry: docker-compose run --rm backend bash -c "pre-commit run"
      language: system
      types: [python]
      require_serial: true
