version: "3.7"
services:
  backend:
    build:
      target: dev
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - DJANGO_DATABASE_URL=postgres://postgres:postgres@db:5432/jjodel
      - NGINX_PORT=${NGINX_PORT}
      - COMPOSE_FILE=docker-compose.yml
      - USE_DOCKER=True
      - COMPOSE_PROJECT_NAME=jjodel
    depends_on:
      - db
    user: ${LOCAL_USER_ID}
  db:
    image: postgres:14.2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jjodel
    ports:
      - "55434:5432"
volumes:
  db_data:
